{
	{name="zlan", cat="util", path="lib/util_zlan.velx"},
	{name="cpio", cat="util", path="lib/util_cpio.velx"},
	{name="velx", cat="util", path="mods/util_velx.velx"},
	{name="urf", cat="util", path="lib/util_urf.velx"},
	{name="vcomponent", cat="util", path="lib/util_vcomponent.velx"},
	{name="oefiv2", cat="util", path="mods/util_oefiv2.velx"},
	{name="oefiv1", cat="util", path="mods/util_oefiv1.velx"},
	{name="openos", cat="loader", path="mods/loader_openos.velx"},
	{name="monolith", cat="loader", path="mods/loader_monolith.velx"},
	{name="fuchas", cat="loader", path="mods/loader_fuchas.velx"},
	{name="vbios", cat="vdev", path="mods/vdev_vbios.velx"},
	{name="biosdev", cat="vdev", path="mods/vdev_biosdev.velx"},
	{name="searchpaths", cat="util", path="mods/util_searchpaths.velx"},
	{name="vfs", cat="core", path="mods/vfs.velx"},
	--{name="tsuki", cat="loader", path="mods/loader_tsuki.zy2m"},
	--{name="romfs", cat="util", path="mods/util_romfs.zy2m"},
	{name="cpio", cat="util", path="lib/util_cpio.velx"},
	--{name="frequest", cat="util", path="mods/util_frequest.zy2m"},
	--{name="loadfile", cat="loader", path="mods/loader_loadfile.zy2m"},
	{name="minitel", cat="net", path="lib/net_minitel.velx"},
	--{name="vdev", cat="util", path="mods/util_vdev.zy2m"},
	{name="classic", cat="menu", path="mods/menu_classic.velx"},
	{name="luaconsole", cat="util", path="mods/util_luaconsole.velx"},
	--{name="vdevrt", cat="rtmod", path="mods/rtmod_vdevrt.zy2m"},
	--{name="tsukinet", cat="net", path="mods/net_tsukinet"},
	--{name="biosemu", cat="loader", path="mods/loader_biosemu.zy2m", warning="warn_mod_biosemu"},
	--{name="zflash", cat="rtmod", path="mods/rtmod_zflash.zy2m", warning="warn_mod_zflash"},
	--{name="bioscomp", cat="vdev", path="mods/vdev_bioscomp.zy2m"},
	--{name="luadata", cat="vdev", path="mods/vdev_luadata.zy2m"}
}