{
	{name="zlan", cat="util", path="lib/util_zlan.zy2l"},
	{name="cpio", cat="util", path="lib/util_cpio.zy2l"},
	{name="urf", cat="util", path="lib/util_urf.zy2l"},
	{name="vcomponent", cat="util", path="lib/util_vcomponent.zy2l"},
	{name="oefiv2", cat="util", path="mods/util_oefiv2.zy2m"},
	{name="oefiv1", cat="util", path="mods/util_oefiv1.zy2m"},
	{name="openos", cat="loader", path="mods/loader_openos.zy2m"},
	{name="fuchas", cat="loader", path="mods/loader_fuchas.zy2m"},
	{name="vbios", cat="vdev", path="mods/vdev_vbios.zy2m"},
	{name="biosdev", cat="vdev", path="mods/vdev_biosdev.zy2m"},
	{name="searchpaths", cat="util", path="mods/util_searchpaths.zy2m"},
	--{name="tsuki", cat="loader", path="mods/loader_tsuki.zy2m"},
	--{name="romfs", cat="util", path="mods/util_romfs.zy2m"},
	{name="cpio", cat="util", path="lib/util_cpio.zy2l"},
	--{name="frequest", cat="util", path="mods/util_frequest.zy2m"},
	--{name="loadfile", cat="loader", path="mods/loader_loadfile.zy2m"},
	{name="minitel", cat="net", path="lib/net_minitel.zy2l"},
	--{name="vdev", cat="util", path="mods/util_vdev.zy2m"},
	{name="classic", cat="menu", path="mods/menu_classic.zy2m"},
	--{name="vdevrt", cat="rtmod", path="mods/rtmod_vdevrt.zy2m"},
	--{name="tsukinet", cat="net", path="mods/net_tsukinet"},
	--{name="biosemu", cat="loader", path="mods/loader_biosemu.zy2m", warning="warn_mod_biosemu"},
	--{name="zflash", cat="rtmod", path="mods/rtmod_zflash.zy2m", warning="warn_mod_zflash"},
	--{name="bioscomp", cat="vdev", path="mods/vdev_bioscomp.zy2m"},
	--{name="luadata", cat="vdev", path="mods/vdev_luadata.zy2m"}
}